### ISSUE TITLE
Overview of edit functionality to user details (ProfileDetails component)

### ISSUE THREAD

**Issue by NicoleLatifi** [gabichuelas/crate#29]
**This card is still open for documentation purposes, but tasks within have been split into other cards**

The Profile component will render:

ProfileDetails component:
- Add/Edit profile picture
- Edit email address
- Add/Edit shipping address
- Add/Edit personal description

This component will initially render the information that exists in state upon load (i.e. if the user already has a picture/shipping/description)

Edit button:
When a user clicks 'Edit', all details will turn to input fields for a user to edit all at once. The placeholder text will either be 'Enter new...' or the information that exists for that category.

Save button:
When the user is done entering the new/changed information, the save button will make a post request to submit all categories.

**Comment by gabichuelas** [comment]
This snippet might be similar to what will end up being added to the user/api/actions.js file:

```
// Update user profile
export function updateProfile() {
  return dispatch => {
    return axios.post(routeApi, mutation({
      operation: 'updateUser',
      fields: ['id', 'name', 'description', 'email', 'address', 'image']
    }))
  }
}
```
