### ISSUE TITLE
Understand what order history data from the backend will look like.

### ISSUE THREAD

**Issue by NicoleLatifi** [gabichuelas/crate#63]
We have a general understanding of what the order history tables look like but need to see exactly what the API is going to give back to us so that we can continue building out the OrderHistory component.

**Comment by gabichuelas** [comment]
@NicoleLatifi this is turning out to be a little more difficult than expected.. So far I've managed to write a query to get a list of orders that belong to the logged in / authorized user. That's using the query called `ordersByUser`. 

Next step is to figure out how to get the products for each of those orders, which is the part I'm really stuck on.
